### ISSUE TITLE
遇到错误：使用Gradle构建继承时找不到SimpleEngine，下载源码使用库工程的时候，项目都是错误，无法使用，，，，

### ISSUE THREAD

**Issue by wblyuyang** [lfkdsk/JustWeEngine#13]
找到问题了，路径文件夹名称首字母都是大写，而项目中的路径都是小写
![qq 20170101163642](https://cloud.githubusercontent.com/assets/9973440/21580631/cff0e114-d040-11e6-8369-3207c4d69848.png)

**Comment by ice1000** [comment]
楼主暂时可以使用下载源码的方式构建。

**Comment by lfkdsk** [comment]
@wblyuyang 多谢反馈，已经修好了，git对路径的大小写不敏感造成了诡异的问题。

``` groovy

	dependencies {
	        compile 'com.github.lfkdsk:JustWeEngine:v1.13'
	}

``` 

gradle的地址也更新好了
