### ISSUE TITLE
请问现有两组帧动画如何来切换当前显示

### ISSUE THREAD

**Issue by hookbin** [lfkdsk/JustWeEngine#14]
请问现有两组帧动画如何来切换当前显示

```
BaseSprite{
      private LinkedList<Rect> s_frame_rect;
}
```

**Comment by lfkdsk** [comment]
是指连续的帧动画么？

**Comment by hookbin** [comment]
@lfkdsk 两组连续的帧动画

**Comment by lfkdsk** [comment]
你可以把之前的动画`remove`掉，然后再`add`进新的动画。

**Comment by hookbin** [comment]
@lfkdsk 现在是这样写的,完成了两组帧动画
` //DefaultFrameAnim
        addRectFrame(PERSON_W * 0, 0, PERSON_W, PERSON_H);
        addRectFrame(PERSON_W * 2, 0, PERSON_W, PERSON_H);
        addfixedAnimation(ANIM_DEFAULT, new FrameAnimation(0, 1, 1));
        //JumpFrameAnim
        addRectFrame(PERSON_W * 0, 0, PERSON_W, PERSON_H);
        addRectFrame(PERSON_W * 1, 0, PERSON_W, PERSON_H);
        addfixedAnimation(ANIM_JUMP, new FrameAnimation(2, 3, 1));`

我想要切换单帧时用什么方法来完成呢

**Comment by ice1000** [comment]
和Frice实现这种动画一样啊 😂
