### ISSUE TITLE
errors in project

### ISSUE THREAD

**Issue by Dagye95** [lfkdsk/JustWeEngine#16]
i downloaded the program and ran it in eclipse and it had 990 errors, Ive corrected some of them but I wanted to know is it the code or the program that is faulty

**Comment by lfkdsk** [comment]
Which version did you download? Master branch is in developing may have some errors but wont be 990 errors. And Android studio's project may not be converted to eclipse project.

**Comment by lfkdsk** [comment]
May be you can support some details about errors.

**Comment by Dagye95** [comment]
I Forked the master file, some of the errors that popped up for example for basicanim.java said that float2 was wrong and  should be changed to float and the import should be "import java.awt.geom.Arc2D.Float;
" or one of the other 5 available but i suspect you're using a 2d theme so i mentioned this one, also there a number of error with the imported packages saying theyre unused but that may be langauge program I am using

**Comment by lfkdsk** [comment]
`Float2` is a real exist `Class` in `android.renderscript` bundle. At least, I can use it with API15 SDK. Please Check you Android SDK Version. I suggest to use release version just like last release [v1.13](https://github.com/lfkdsk/JustWeEngine/releases/tag/v1.13) . 
In fact, this project can be built successful.
![image](https://cloud.githubusercontent.com/assets/11584398/23386568/13b2d7ee-fd92-11e6-8cfd-2aba72707005.png)
just like this picture.
And in other [issues](https://github.com/lfkdsk/JustWeEngine/issues), they focus on some details in using this framework ,not build this framework. So I think it can also be built in your computer. Let me know more about you errors in your IDE(With picture better).

**Comment by lfkdsk** [comment]
And, I suggest you use `Android Studio` as your android IDE. Eclipse was an awesome IDE for java developers. But it is not good enough for nowadays Android developers(It stoped update at 12/2015). With Android Studio, you can build and add dependent lib with `gradle`:

With Gradle:

Step 1. Add the JitPack repository to your build file
Add it in your root build.gradle at the end of repositories:
``` groovy
      allprojects {
      repositories {
          ...
          maven { url "https://jitpack.io" }
      }
  }
``` 

Step 2. Add the dependency
``` groovy
    dependencies {
        compile 'com.github.lfkdsk:JustWeEngine:v1.13'
  }  
```

**Comment by Dagye95** [comment]
Very interesting, i also have a game on my repository that i recently made through eclipse, i was wondering if you could please have a look and see what i am missing or improve on

**Comment by lfkdsk** [comment]
you copyed code to your repo? Android SDK version is?

**Comment by Dagye95** [comment]
Yes if you check my repo under Bounce-game you'll the java game I created in eclipse, I don't think it will support android. 

And when I try to run the program in android it does not launch

**Comment by lfkdsk** [comment]
justweengine now is an engine only support Android platform. desktop version is under developing. java game cannot run in Android directly.

**Comment by Dagye95** [comment]
I know but there is a project on my page that I would like feedback on if you have the time, called Bounce-game

**Comment by ice1000** [comment]
Desktop game engine?
Try [Frice Engine](https://github.com/icela/FriceEngine)。
