### ISSUE TITLE
如何在JustWeEngine中使用原生控件?

### ISSUE THREAD

**Issue by hookbin** [lfkdsk/JustWeEngine#17]
虽然在JustWeEngine中支持TextButton,GameTextPrinter 等多种控件,但是往往无法像View一样使用它们,
例如：TextButton的width&height 无法获取便无法进行准确的放置定位。

**Comment by lfkdsk** [comment]
唔，从现在看来确实存在这个问题部分继承`GameTextPrinter`的控件当时没有提供宽高的支持这确实是一个问题，但解决思路已经有了，会陆续抽时间实现，比如我的这个`lib`：[JustUiKit](https://github.com/lfkdsk/JustUiKit) 提供了简便成型的方式去制作`LinearLayout`,`RelativeLayout`,`FrameLayout`等控件，把这种思路移植到`JustWeEngine`中甚至可以实现各种布局的使用。

**Comment by hookbin** [comment]
@lfkdsk 虽然这是一个问题,如果我想在Activity中使用原生控件的话我该如何去做呢?

**Comment by lfkdsk** [comment]
@hookbin `master`分支上已经对此进行了修改，surfaceView外层套了一个FrameLayout，应该能暂且解决你说的问题。

**Comment by hookbin** [comment]
好的 谢谢了
