### ISSUE TITLE
是否可以考虑简化调用代码书写？

### ISSUE THREAD

**Issue by WenruiCui** [lfkdsk/JustWeEngine#6]
rt，部分代码是不是可以考虑提供注解的方式来进行调用？

**Comment by ice1000** [comment]
想太多，Java就是这样的风格，最好不要标新立异。
最优秀的代码是不需要注释的，它们自己注释自己 :joy:

**Comment by lfkdsk** [comment]
@WenruiCui 其实我会比较担心注解调用的性能。

**Comment by WenruiCui** [comment]
之前看过一个分析，在android上面注解牺牲的性能现在基本可以忽略，因为 毫秒级的时间损耗在移动端app上面影响极其微小，
