### ISSUE TITLE
关于数据库的问题

### ISSUE THREAD

**Issue by ice1000** [lfkdsk/JustWeEngine#7]
前面描述的SharedPreference打不开的问题在我简单看了你的Engine类以后解决了(生命周期的问题，我以前在构造方法里面构造Preference,真是傻透了)，还有就是希望引擎本身也能包含Node类那个库

**Comment by ice1000** [comment]
我在studio里面直接创建类 然后把你的readme里面的代码放进去，然后满屏姨妈红。。。
QQ 951394653

**Comment by ice1000** [comment]
还有，我手动导入jw失败了，最后是改的demo的源码，改了下engine的源码，把那个好像是调试数据的东西去掉了。。。另外问问怎么去掉碰撞框

**Comment by lfkdsk** [comment]
tools里面有个`SpUtils` 可以直接使用 `SpUtils.get/put`的方法进行存储取出=-=，封装了SharedPreference

**Comment by lfkdsk** [comment]
jw无法导入是因为Gradle的问题么？另外demo里面的jw版本是很老的，所以没有数据库这些后加的功能。只要能导入最新的版本的话，就可以用啦！

**Comment by lfkdsk** [comment]
@ice1000 另外加你QQ并没有回应啊=-=

**Comment by ice1000** [comment]
嗯。。。。好的 我回去试试。。
很大原因可能是因为没有网络

**Comment by ice1000** [comment]
我试了试 直接把demo里面的engine模块删了 再把clone下来的粘回去 build不出来。。。
